### ISSUE TITLE
[Typo in Readme]

### ISSUE THREAD

**Issue by tayjaybabee** [Inspyre-Technologies/FX-SCP#2]
It reads 'fx-scp' when it should read 'fx_scp'.

We will work on which name we should go with later, but for now fix this pls.

Naming options (for later)

fxscp
fx-scp

**Comment by doubledave** [comment]
fixed in commit: 342aef4

Assigning for review: tayjaybabee

Merge request: #3

**Comment by tayjaybabee** [comment]
Code reviewed

Merge approved.

Rebased & Merged in issue #3 

Fixed by: @doubledave
